name: Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Install godoc
        run: sudo apt install golang-go.tools

      - name: Checkout the code
        uses: actions/checkout@master

      - name: Build the godoc
        run: ./docs.sh

      - name: Push to Docs
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          directory: 'docs-build'
          repository: 'GIFTS-fs/Docs'
